"""
This file is used to collect various CSS files and create a master CSS file.
Files should be located in  directory ./parts, that is a folder named parts inside where the script is ran.
The output will be a file "master.css" located in the directory from which the script is ran.

author -- Daniel Jacob Behnke
email -- djbehnke.mail@gmail.com
date -- 06/15/18
"""

import os
import datetime


def main():
    """Calls functions to read all CSS files then write them to the master file"""
    write_master(make_file())


def make_file():
    """
    Creates a String of all the contents from all CSS files.
    Added information includes a timestamp as well as separators for when the contents of each file begins.

    returns:
    a String of all the CSS files plus helpful information
    """
    contents = ("/*This file was created automatically with the makeMaster.py script.\n"
                + "Time of creation: " + str(datetime.datetime.now()) + "*/")

    for filename in os.listdir('parts'):
        contents += "\n\n/* !!! Begin File " + filename + " !!! */\n\n"
        contents += read_file(filename)

    return contents


def write_master(contents):
    """
    Will write contents to master.css


    Keyword arguments:
    contents -- the CSS code to be written, generated by make_file()
    """
    with open("master.css", 'w') as f:
        f.write(contents)


def read_file(filename):
    """
    Actually reads the file

    Keyword arguments:
    filename -- the filename to read, generated by make_file()

    returns:
    the entire contents of the file
    """
    with open(os.path.join("parts", filename), 'r') as f:
        return f.read()


if __name__ == "__main__":  # Only calls the main method if run directly
    main()
